# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Film.delete_all
# Film.create(:filmname => 'Adventures of Robin Hood, The', :description => 'Errol Flynn in swashbucklingly good form as the friend to the poor in this richly colourful rendition of the legend', :price => '9.99', :director => 'Michael Curtiz, William Keighley', :actors => 'Errol Flynn, Olivia deHavilland, Basil Rathbone, Claude Rains', :length => '102 minutes', :score => 0, :release_year => '1938', :image_url => 'robin_hood.jpg')
# Film.create(:filmname => 'All The President\'s Men', :description => 'The consequences of the Watergate break-in, and the events leading up to the only ever Presidential resignation in US history', :price => '12.99', :director => 'Alan J. Pakula', :actors => 'Robert Redford, Dustin Hoffman, Hal Holbrook, Jason Robards Jr.', :length => '138 minutes', :score => 0, :release_year => '1976', :image_url => 'presidents_men.jpg')
# Film.create(:filmname => 'All The King\'s Men', :description => 'Oscar-winning turns from Broderick Crawford and Mercedes McCambridge in a political drama', :price => '11.99', :director => 'Robert Rossen', :actors => 'Broderick Crawford, John Ireland, Mercedes McCambridge', :length => '109 minutes', :score => 0, :release_year => '1949', :image_url => 'all_the_kings_men.jpg')
# Film.create(:filmname => 'Bad Day At Black Rock', :description => 'A one-armed man arrives alone at a railway station shortly after the end of the Second World War. He is carrying a secret which causes  tensions among the locals.', :price => '11.99', :director => 'John Sturges', :actors => 'Spencer Tracy, Lee Marvin, Robert Ryan', :length => '81 minutes', :score => 0, :release_year => '1955', :image_url => 'black_rock.jpg')
# Film.create(:filmname => 'Ben-Hur', :description => 'A Judean aristocrat loses everything when he refuses to help an old friend (now a Roman officer) locate terrorists in the Holy Land', :price => '11.99', :director => 'William Wyler', :actors => 'Charlton Heston, Jack Hawkins, Stephen Boyd', :length => '212 minutes', :score => 0, :release_year => '1959', :image_url => 'ben_hur.jpg')
# Film.create(:filmname => 'Seven Samurai', :description => 'Epic Japanese movie - heavily inspired by american westerns - which was itself was the inspiration for one of the best, The Magnificent Seven', :price => '19.99', :director => 'Akira Kusosawa', :actors => 'Takashi Shimura, Toshiro Mifune', :length => '217 minutes', :score => 0, :release_year => '1954', :image_url => 'seven_samurai.jpg')
# Film.create(:filmname => 'Casablanca', :description => 'Rick Blaine and Ilsa Lund meet again in the north African city, but everything has changed for the worse for both of them', :price => '11.99', :director => 'Michael Curtiz', :actors => 'Humphrey Bogart, Ingrid Bergman, Paul Henreid, Claude Rains', :length => '102 minutes', :score => 0, :release_year => '1943', :image_url => 'casablanca.jpg')
# Film.create(:filmname => 'Harvey', :description => 'Pixillated Jimmy Stewart is best friends with a giant invisible rabbit, and his sister is going insane because of it.', :price => '12.99', :director => 'Henry Koster', :actors => 'James Stewart, Josephine Hull, Peggy Dow', :length => '104 minutes', :score => 0, :release_year => '1950', :image_url => 'harvey.jpg')
# Film.create(:filmname => 'Citizen Kane', :description => 'A whole, extraordinary life unfolds as Orson Welles leads us through the long-standing "best film of all time"', :price => '19.99', :director => 'Orson Welles', :actors => 'Orson Welles, Joseph Cotton, Dorothy Comingore', :length => '119 minutes', :score => 0, :release_year => '1941', :image_url => 'citizen_kane.jpg')
# Film.create(:filmname => 'Hud', :description => 'Paul Newman is broodiness at its best in this modern western. Expect much angst and alienation', :price => '12.99', :director => 'Martin ritt', :actors => 'Paul Newman, Patricia Neal, Melvyn Douglas', :length => '112 minutes', :score => 0, :release_year => '1963', :image_url => 'hud.jpg')
# Film.create(:filmname => 'Rope', :description => 'Psychological thriller based on the Leopold and Loeb case, in which two young men demonstrate their superiority by committing a murder', :price => '13.99', :director => 'Alfred Hitchcock', :actors => 'James Stewart, Farley Grainger, John Dahl, Joan Chandler, Constance Collier', :length => '90 minutes', :score => 0, :release_year => '1950', :image_url => 'rope.jpg')
# Film.create(:filmname => 'Hunchback of Notre Dame, The', :description => 'Based on the classic Victor Hugo novel, this is a provocative and moving study of alienation and faith', :price => '13.99', :director => 'William Dieterle', :actors => 'Charles Laughton, Maureen O\'Hara, Cedric Hardwicke', :length => '95 minutes', :score => 0, :release_year => '1939', :image_url => 'hunchback.jpg')
Film.create(:filmname => 'Gone With The Wind', :description => 'The biggest Civil War epic of them all, as Rhett Butler tries to win over spoiled brat Scarlett O\'Hara', :price => '12.99', :director => 'Victor Fleming', :actors => 'Vivien Leigh, Clark Gable, Olivia deHavilland', :length => '220 minutes', :score => 0, :release_year => '1939', :image_url => 'gone_with_the_wind.jpg')
Film.create(:filmname => 'Deer Hunter, The', :description => 'A group of steelworkers go off to fight in Vietnam, and are helpless to prevent their lives falling apart around them', :price => '19.99', :director => 'Michael Cimino', :actors => 'Robert DeNiro, Meryl Streep, Christopher Walken, John Cazale, John Savage', :length => '183 minutes', :score => 0, :release_year => '1978', :image_url => 'deer_hunter.jpg')
Film.create(:filmname => 'Rear Window', :description => 'Set almost entirely in one room, a gripping thriller in which a photographer, laid up with a broken leg, believes he has witnessed a murder.', :price => '12.99', :director => 'Alfred Hitchcock', :actors => 'James Stewart, Grace Kelly, Thelma Ritter, Raymond Burr', :length => '112 minutes', :score => 0, :release_year => '1954', :image_url => 'rear_window.jpg')
Film.create(:filmname => 'Out Of Sight', :description => 'Based on an Elmore Leonard novel, it describes the odd relationship which blooms between a career bank robber and the US Marshall chasing him', :price => '13.99', :director => 'Steven Soderbergh', :actors => 'George Clooney, Jennnifer Lopez, Steve Zahn, Don Cheadle', :length => '122 minutes', :score => 0, :release_year => '1998', :image_url => 'out_of_sight.jpg')
